# -*- coding: utf-8 -*-
"""Agentic GraphRAG luồng.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TDE-zXnapVW_NjnrKHSmIQhrn2fw6W57
"""

!pip install langchain-groq langchain neo4j

import re
import json
from typing import List, Any, Literal

import neo4j
from neo4j import GraphDatabase
from langchain_groq import ChatGroq

from google.colab import userdata
GROQ_API_KEY = userdata.get('GROQ_API_KEY')
NEO4J_URI = userdata.get('NEO4J_URI')
NEO4J_USERNAME = userdata.get('NEO4J_USERNAME')
NEO4J_PASSWORD = userdata.get('NEO4J_PASSWORD')
NEO4J_DATABASE = userdata.get('NEO4J_DATABASE')

driver = GraphDatabase.driver(NEO4J_URI,
    auth=(NEO4J_USERNAME, NEO4J_PASSWORD),
    notifications_min_severity="OFF"
)

# KHỞI TẠO LLM GROQ CHUNG
def chat(messages, **config):
    llm = ChatGroq(api_key=GROQ_API_KEY, model="meta-llama/llama-4-scout-17b-16e-instruct", temperature=0, max_tokens=2048)
    return llm.invoke(messages, **config).content

NODE_PROPERTIES_QUERY = """
CALL apoc.meta.data()
YIELD label, other, elementType, type, property
WHERE NOT type = "RELATIONSHIP" AND elementType = "node"
WITH label AS nodeLabels, collect({property:property, type:type}) AS properties
RETURN {labels: nodeLabels, properties: properties} AS output
"""
REL_PROPERTIES_QUERY = """
CALL apoc.meta.data()
YIELD label, other, elementType, type, property
WHERE elementType = "relationship" AND type <> "RELATIONSHIP"
WITH label AS relType, collect({property:property, type:type}) AS properties
RETURN {type: relType, properties: properties} AS output
"""
REL_QUERY = """
CALL apoc.meta.data()
YIELD label, other, elementType, type, property
WHERE type = "RELATIONSHIP" AND elementType = "node"
UNWIND other AS other_node
RETURN {start: label, type: property, end: toString(other_node)} AS output
"""

def get_structured_schema(driver: neo4j.Driver) -> dict[str, Any]:
    node_labels_response = driver.execute_query(NODE_PROPERTIES_QUERY)
    node_properties = [
        data["output"] for data in [r.data() for r in node_labels_response.records]
    ]

    rel_properties_query_response = driver.execute_query(REL_PROPERTIES_QUERY)
    rel_properties = [
        data["output"]
        for data in [r.data() for r in rel_properties_query_response.records]
    ]

    rel_query_response = driver.execute_query(REL_QUERY)
    relationships = [
        data["output"] for data in [r.data() for r in rel_query_response.records]
    ]

    return {
        "node_props": {el["labels"]: el["properties"] for el in node_properties},
        "rel_props": {el["type"]: el["properties"] for el in rel_properties},
        "relationships": relationships,
    }

def get_schema(driver: neo4j.Driver) -> str:
    structured_schema = get_structured_schema(driver)

    def _format_props(props: list[dict[str, Any]]) -> str:
        return ", ".join([f"{prop['property']}: {prop['type']}" for prop in props])
    formatted_node_props = [
        f"{label} {{{_format_props(props)}}}"
        for label, props in structured_schema["node_props"].items()
    ]

    formatted_rel_props = [
        f"{rel_type} {{{_format_props(props)}}}"
        for rel_type, props in structured_schema["rel_props"].items()
    ]

    formatted_rels = [
        f"(:{element['start']})-[:{element['type']}]->(:{element['end']})"
        for element in structured_schema["relationships"]
    ]

    return "\n".join(
        [
            "Thuộc tính của Node (Node properties):",
            "\n".join(formatted_node_props),
            "Thuộc tính của Quan hệ (Relationship properties):",
            "\n".join(formatted_rel_props),
            "Các mối quan hệ (The relationships):",
            "\n".join(formatted_rels),
        ]
    )

print(get_schema(driver))

####################################################
#```Cypher```, ```json``` strippers from llm output#
####################################################

def strip_code_fences(text: str) -> str:
    text = text.strip()
    # remove ```json or ``` and closing ```
    text = re.sub(r"^```json\s*|^```\s*|```$", "", text, flags=re.IGNORECASE).strip()
    return text

def strip_code_cypher(text: str) -> str:
    text = text.strip()
    # remove ```json or ``` and closing ```
    text = re.sub(r"^```(?:\w+)?\s*|```$", "", text, flags=re.IGNORECASE).strip()
    return text

# # TEXT-TO-CYPHER AGENT
# prompt_template = {
#     "static": {
#         "instructions": """
#     Hướng dẫn:
#     Hãy sinh ra câu lệnh Cypher để truy vấn cơ sở dữ liệu đồ thị nhằm lấy dữ liệu trả lời cho câu hỏi của người dùng dưới đây.

#     QUY TẮC SINH CYPHER BẮT BUỘC (CRITICAL RULES):
#     1. ĐƯỜNG ĐI ĐẾN LUẬT (Path to Law): Để chạm tới các node làm căn cứ pháp luật (DieuLuat, DieuKhoanLuat, DieuKhoanDiemLuat), KHÔNG chỉ dùng duy nhất `CAN_CU_THEO`. Hãy linh hoạt cho phép path đi qua các node trung gian bằng cú pháp: `-[:DAN_DEN_HE_QUA|YEU_CAU_DIEU_KIEN|CAN_CU_THEO*0..3]->(luat_goc)`.
#     2. CHIẾN THUẬT VÉT LUẬT (Tree Traversal): Khi đã tìm thấy node luật gốc, BẮT BUỘC phải sử dụng quét chiều sâu để lấy toàn bộ điểm/khoản liên quan bằng cú pháp: `OPTIONAL MATCH (luat_goc)-[:CO_KHOAN|CO_DIEM*0..2]->(luat_detail)`.
#     3. SỬ DỤNG ID (Strict ID Matching): Tên node và ID phải khớp 100% với danh sách được cung cấp. KHÔNG tự bịa lỗi chính tả, thêm bớt ký tự.
#     Hướng dẫn định dạng:
#     Không bao gồm bất kỳ lời giải thích hay lời xin lỗi nào trong câu trả lời của bạn.
#     CHỈ TRẢ LỜI BẰNG CYPHER, KHÔNG SỬ DỤNG CODEBLOCKS (```).
#     """
#     },
#     "dynamic": {
#         "schema": """
#     Lược đồ Cơ sở dữ liệu Đồ thị (Schema) và Danh sách ID hợp lệ:
#     Chỉ sử dụng các loại quan hệ và thuộc tính được cung cấp trong lược đồ dưới đây.
#     {}
#     """,
#         "terminology": """
#     Ánh xạ thuật ngữ (Terminology mapping):
#     {}
#     """,
#         "examples": """
#     Ví dụ (Examples):
#     {}
#     """,
#         "question": """
#     Câu hỏi của người dùng: {}
#     """,
#     },
# }

# class Text2Cypher:
#     def __init__(self, driver: neo4j.Driver):
#         self.driver = driver
#         self.dynamic_sections = {}
#         self.required_sections = ["question"]
#         self.prompt_template = prompt_template

#         schema_string = get_schema(driver)
#         self.set_prompt_section("schema", schema_string)

#     def set_prompt_section(
#         self,
#         section: Literal["terminology", "examples", "schema", "question"],
#         value: str,
#     ):
#         self.dynamic_sections[section] = value

#     def get_full_prompt(self):
#         prompt = self.prompt_template["static"]["instructions"]
#         for section in self.prompt_template["dynamic"]:
#             if section in self.dynamic_sections:
#                 prompt += self.prompt_template["dynamic"][section].format(
#                     self.dynamic_sections[section]
#                 )
#         return prompt

#     def generate_cypher(self):
#         for section in self.required_sections:
#             if section not in self.dynamic_sections:
#                 raise ValueError(
#                     f"Phần {section} là bắt buộc để tạo prompt. Sử dụng set_prompt_section để thiết lập nó."
#                 )
#         prompt = self.get_full_prompt()
#         cypher = chat(messages=[{"role": "user", "content": prompt}])
#         return strip_code_cypher(cypher)

# TEXT-TO-CYPHER AGENT
prompt_template = {
    "static": {
        "instructions": """
    Bạn là một chuyên gia truy xuất Cơ sở dữ liệu Đồ thị pháp luật (Legal Graph Database) sử dụng ngôn ngữ Neo4j Cypher.
    Nhiệm vụ của bạn là đọc câu hỏi của người dùng, phân tích thông tin các node được cung cấp, và viết một câu lệnh Cypher để lấy về toàn bộ ngữ cảnh pháp lý cần thiết.

    QUY TẮC SINH LỆNH CYPHER (CRITICAL RULES):
    1. LỰA CHỌN ID CHÍNH XÁC (ID Selection): Đọc phần "Thông tin về các node căn cứ pháp luật". Xác định Điều luật nào phù hợp để trả lời câu hỏi và sử dụng chính xác ID đó trong lệnh `MATCH (n {id: "..."})`, có thể có nhiều hơn 1 Điều luật cần để trả lời cho câu hỏi. KHÔNG tự bịa ID ngoài danh sách.
    2. VÉT CẠN CẤU TRÚC LUẬT (Top-Down Traversal): Một Điều luật luôn chứa các Khoản và Điểm. BẮT BUỘC sử dụng cú pháp `OPTIONAL MATCH (n)-[:CO_KHOAN|CO_DIEM*0..2]->(chi_tiet)` để lấy trọn vẹn nội dung của Điều luật đó.
    3. XỬ LÝ THAM CHIẾU CHÉO (Cross-References): Pháp luật thường tham chiếu đến nhau. TỪ các node `chi_tiet` vừa tìm được, BẮT BUỘC phải dùng `OPTIONAL MATCH (chi_tiet)-[:THAM_CHIEU_DEN]->(luat_lien_quan)` để tìm các luật liên đới, sau đó vét cạn cấu trúc của luật liên đới đó (nếu có).
    4. ĐỊNH DẠNG ĐẦU RA JSON (JSON Context Packaging): KHÔNG trả về kết quả dạng bảng nhiều dòng. Bắt buộc dùng `WITH` và `collect(DISTINCT {...})` để gom nhóm toàn bộ nội dung luật chính và luật tham chiếu vào chung một Object (Dictionary) duy nhất trả về bằng `RETURN`.

    HƯỚNG DẪN ĐẦU RA (OUTPUT FORMATTING):
    - KHÔNG giải thích, phân tích hay xin lỗi.
    - CHỈ TRẢ LỜI BẰNG LỆNH CYPHER THUẦN TÚY.
    - KHÔNG SỬ DỤNG CODEBLOCKS (ví dụ: không dùng ```cypher ... ```).
    """
    },
    "dynamic": {
        "schema": """
    Lược đồ Cơ sở dữ liệu Đồ thị (Schema) và Danh sách ID hợp lệ:
    Chỉ sử dụng các loại quan hệ và thuộc tính được cung cấp trong lược đồ dưới đây.
    {}
    """,
        "terminology": """
    Ánh xạ thuật ngữ (Terminology mapping):
    {}
    """,
        "examples": """
    Ví dụ (Examples):
    {}
    """,
        "question": """
    Câu hỏi của người dùng: {}
    """,
    },
}

class Text2Cypher:
    def __init__(self, driver: neo4j.Driver):
        self.driver = driver
        self.dynamic_sections = {}
        self.required_sections = ["question"]
        self.prompt_template = prompt_template

        schema_string = get_schema(driver)
        self.set_prompt_section("schema", schema_string)

    def set_prompt_section(
        self,
        section: Literal["terminology", "examples", "schema", "question"],
        value: str,
    ):
        self.dynamic_sections[section] = value

    def get_full_prompt(self):
        prompt = self.prompt_template["static"]["instructions"]
        for section in self.prompt_template["dynamic"]:
            if section in self.dynamic_sections:
                prompt += self.prompt_template["dynamic"][section].format(
                    self.dynamic_sections[section]
                )
        return prompt

    def generate_cypher(self):
        for section in self.required_sections:
            if section not in self.dynamic_sections:
                raise ValueError(
                    f"Phần {section} là bắt buộc để tạo prompt. Sử dụng set_prompt_section để thiết lập nó."
                )
        prompt = self.get_full_prompt()
        cypher = chat(messages=[{"role": "user", "content": prompt}])
        return strip_code_cypher(cypher)

# TOOLS VÀ MÔ TẢ
answer_given_description = {
    "type": "function",
    "function": {
        "name": "respond",
        "description": "Nếu cuộc hội thoại đã chứa một câu trả lời hoàn chỉnh cho câu hỏi, hãy sử dụng công cụ này để trích xuất nó. Ngoài ra, nếu người dùng trò chuyện phiếm, hãy dùng công cụ này để nhắc họ rằng bạn chỉ có thể trả lời các câu hỏi liên quan đến luật hôn nhân gia đình.",
        "parameters": {
            "type": "object",
            "properties": {
                "answer": {
                    "type": "string",
                    "description": "Phản hồi trực tiếp bằng câu trả lời",
                }
            },
            "required": ["answer"],
        },
    },
}

def answer_given(answer: str):
    """Trích xuất câu trả lời từ đoạn văn bản đã cho."""
    return answer

text2cypher_description = {
    "type": "function",
    "function": {
        "name": "text2cypher",
        "description": "Truy vấn cơ sở dữ liệu đồ thị bằng câu hỏi của người dùng. Khi các công cụ khác không phù hợp, hãy sử dụng công cụ này làm phương án dự phòng (fallback).",
        "parameters": {
            "type": "object",
            "properties": {
                "question": {
                    "type": "string",
                    "description": "Câu hỏi của người dùng cần tìm câu trả lời",
                }
            },
            "required": ["question"],
        },
    },
}

def text2cypher(question: str):
    """Truy vấn cơ sở dữ liệu bằng câu hỏi của người dùng."""
    t2c = Text2Cypher(driver)
    t2c.set_prompt_section("question", question)
    cypher = t2c.generate_cypher()
    try:
        records, _, _ = driver.execute_query(cypher)
        print('neo4j data:', [record.data() for record in records])
        return [record.data() for record in records]
    except Exception as e:
        return [f"Câu lệnh {cypher} gây ra lỗi: {e}"]

# TOOL: ĐIỀU KIỆN KẾT HÔN (DYNAMICAL AGENT)
dieu_kien_ket_hon_description = {
    "type": "function",
    "function": {
        "name": "dieu_kien_ket_hon",
        "description": "Lấy thông tin quy định pháp luật về điều kiện kết hôn, các trường hợp cấm kết hôn.",
        "parameters": {
            "type": "object",
            "properties": {
                "query": {
                    "type": "string",
                    "description": "Câu hỏi cụ thể của người dùng",
                }
            },
            "required": ["query"],
        },
    },
}

def dieu_kien_ket_hon(query: str):
    """
    Tool đóng vai trò agent: sinh Cypher dựa trên schema đặc thù cho kết hôn và thực thi.
    """
    print(f"[Agent dieu_kien_ket_hon] Đang xử lý truy vấn: '{query}'...")

    # 1. Định nghĩa schema cụ thể cho tool này
    marriage_schema = """
    Thuộc tính của node (properties):
    DieuKhoanLuat {id: STRING, chuong: STRING, dieu: STRING, khoan: STRING, noidung: STRING}
    DieuLuat {id: STRING, chuong: STRING, dieu: STRING, noidung: STRING}
    DieuKhoanDiemLuat {id: STRING, chuong: STRING, dieu: STRING, khoan: STRING, noidung: STRING, diem: STRING}

    Các mối quan hệ (The relationships):
    (:DieuKhoanLuat)-[:CO_DIEM]->(:DieuKhoanDiemLuat)
    (:DieuLuat)-[:CO_KHOAN]->(:DieuKhoanLuat)
    (:DieuKhoanLuat)-[:THAM_CHIEU_DEN]->(:DieuKhoanDiemLuat)
    (:DieuKhoanLuat)-[:THAM_CHIEU_DEN]->(:DieuLuat)

    Các node căn cứ pháp luật cần truy vấn: ["Dieu_8"]
    Thông tin về các node căn cứ pháp luật:
    Dieu_8: Điều kiện kết hôn (Độ tuổi, tự nguyện, năng lực hành vi, không thuộc trường hợp cấm).
    """

    # 2. Định nghĩa ví dụ cụ thể cho tool này
    example_marriage = """
    Câu hỏi: Điều kiện kết hôn theo quy định pháp luật là gì?
    Suy luận: Câu hỏi hỏi về điều kiện kết hôn cơ bản, tương ứng với "Dieu_8". Tôi sẽ chọn id "Dieu_8" làm gốc.
    Query Cypher:
    // 1. Chọn node gốc dựa trên ID đã xác định
    MATCH (luat_goc:DieuLuat {id: "Dieu_8"})

    // 2. Lấy toàn bộ nội dung của Điều luật gốc (bao gồm chính nó, Khoản và Điểm)
    OPTIONAL MATCH (luat_goc)-[:CO_KHOAN|CO_DIEM*0..2]->(chi_tiet_goc)

    // 3. Tìm các điều luật tham chiếu chéo (THAM_CHIEU_DEN) - Ví dụ Điều 8 dẫn chiếu sang Điều 5.
    OPTIONAL MATCH (chi_tiet_goc)-[:THAM_CHIEU_DEN]->(luat_THAM_CHIEU_DEN)

    // 4. Nếu có luật liên quan, vét sạch Khoản/Điểm của luật liên quan đó
    OPTIONAL MATCH (luat_THAM_CHIEU_DEN)-[:CO_KHOAN|CO_DIEM*0..2]->(chi_tiet_THAM_CHIEU_DEN)

    // 5. Gom nhóm trả về JSON
    WITH luat_goc,
         collect(DISTINCT {id: chi_tiet_goc.id, noi_dung: chi_tiet_goc.noidung}) AS NoiDungDieuLuatChinh,
         collect(DISTINCT {id: chi_tiet_THAM_CHIEU_DEN.id, noi_dung: chi_tiet_THAM_CHIEU_DEN.noidung}) AS NoiDungThamChieu

    RETURN {
        dieu_luat_ap_dung: luat_goc.id,
        noi_dung_chinh: NoiDungDieuLuatChinh,
        cac_quy_dinh_tham_chieu: NoiDungThamChieu
    } AS Context_TraLoi
    """

    # 3. Khởi tạo Text2Cypher và nạp các phần động
    t2c = Text2Cypher(driver)
    t2c.set_prompt_section("schema", marriage_schema)
    t2c.set_prompt_section("examples", example_marriage)
    t2c.set_prompt_section("question", query)

    # 4. Sinh câu lệnh Cypher
    cypher = t2c.generate_cypher()
    print(f"[Agent dieu_kien_ket_hon] Cypher generated: {cypher}")

    # 5. Thực thi và trả về dữ liệu
    try:
        records, _, _ = driver.execute_query(cypher)
        result = [record.data() for record in records]
        print(f"[Agent dieu_kien_ket_hon] Tìm thấy {len(result)} kết quả.")
        return result
    except Exception as e:
        return [f"Lỗi khi truy vấn dữ liệu kết hôn: {e}"]

# TOOL: KẾT HÔN TRÁI PHÁP LUẬT
ket_hon_trai_phap_luat_description = {
    "type": "function",
    "function": {
        "name": "ket_hon_trai_phap_luat",
        "description": "Truy vấn các quy định về xử lý kết hôn trái pháp luật, quyền yêu cầu hủy kết hôn trái pháp luật và giải quyết hậu quả về tài sản, con cái.",
        "parameters": {
            "type": "object",
            "properties": {
                "query": {
                    "type": "string",
                    "description": "Câu hỏi cụ thể của người dùng"
                }
            },
            "required": ["query"],
        },
    },
}
from pydantic import BaseModel, Field
from typing import List, Optional
# ==========================================
# 1. ĐỊNH NGHĨA CẤU TRÚC JSON LLM CẦN TRẢ VỀ
# ==========================================
class TrichXuatLuat(BaseModel):
    dieu_luat_ids: List[str] = Field(
        description="Danh sách ID điều luật cần dùng. CHỈ ĐƯỢC CHỌN TỪ: ['Dieu_10', 'Dieu_11', 'Dieu_12']"
    )
    thoi_diem_su_kien: Optional[str] = Field(
        description="Ngày/tháng/năm xảy ra sự kiện trong câu hỏi. Định dạng 'DD-MM-YYYY'. Nếu người dùng KHÔNG nhắc đến mốc thời gian, bắt buộc trả về null.",
        default=None
    )

# ==========================================
# 2. HÀM CỦA TOOL
# ==========================================
def ket_hon_trai_phap_luat(query: str):
    """
    Tool xử lý các vấn đề về kết hôn trái pháp luật và hậu quả pháp lý.
    """
    print(f"[Agent ket_hon_trai_phap_luat] Đang xử lý: '{query}'...")

    # --- BƯỚC 1: DÙNG LLM ĐỂ TRÍCH XUẤT ID VÀ THỜI GIAN ---
    prompt_extract = """
    Bạn là chuyên gia xác định căn cứ pháp lý. Đọc câu hỏi của người dùng và chọn ĐÚNG các Điều luật cần thiết.
    Chỉ được phép chọn từ danh sách sau:
    - "Dieu_10": Người có quyền yêu cầu hủy kết hôn trái pháp luật.
    - "Dieu_11": Xử lý việc kết hôn trái pháp luật
    - "Dieu_12": Hậu quả pháp lý của việc hủy kết hôn trái pháp luật
    Bạn cũng cần trích xuất mốc thời gian (nếu có) để hệ thống áp dụng đúng luật thời kỳ đó.
    """

    # Khởi tạo LLM (Nên dùng model chạy nhanh và giỏi JSON như llama3-70b hoặc gpt-4o-mini)
    llm = ChatGroq(api_key=GROQ_API_KEY, model="openai/gpt-oss-120b", temperature=0)
    structured_llm = llm.with_structured_output(TrichXuatLuat)

    messages = [
        {"role": "system", "content": prompt_extract},
        {"role": "user", "content": f"Câu hỏi: {query}"}
    ]

    try:
        # LLM sẽ trả về object chứa dieu_luat_ids và thoi_diem_su_kien
        extraction = structured_llm.invoke(messages)
        target_ids = extraction.dieu_luat_ids
        target_date = extraction.thoi_diem_su_kien
        print(f"[LLM Filter] Chọn IDs: {target_ids} | Thời điểm: {target_date}")

        # Nếu LLM không chọn được ID nào, gán mặc định để tránh lỗi
        if not target_ids:
            target_ids = ["Dieu_10", "Dieu_11", "Dieu_12"]

    except Exception as e:
        print(f"[Lỗi LLM Filter] {e}. Sử dụng mặc định toàn bộ Điều.")
        target_ids = ["Dieu_10", "Dieu_11", "Dieu_12"]
        target_date = None


    # --- BƯỚC 2: CHẠY CYPHER TĨNH (STATIC CYPHER) ---
    # Câu Cypher này xử lý luôn cả: Phân cấp (Khoản/Điểm), Liên quan, Hướng dẫn và Lọc Thời gian
    cypher_query = """
    MATCH (luat_goc:DieuLuat)
    WHERE luat_goc.id IN $danh_sach_id

    // 1. Lấy chi tiết Khoản, Điểm
    OPTIONAL MATCH (luat_goc)-[:CO_KHOAN|CO_DIEM*0..2]->(chi_tiet_goc)

    // 2. BỘ LỌC THỜI GIAN
    // Sử dụng coalesce để nếu $target_date là NULL thì lấy ngày hôm nay date()
    WITH luat_goc, chi_tiet_goc, coalesce($target_date, date()) AS ngay_ap_dung
    WHERE (chi_tiet_goc.ngay_hieu_luc IS NULL OR chi_tiet_goc.ngay_hieu_luc <= ngay_ap_dung)
      AND (chi_tiet_goc.ngay_het_hieu_luc IS NULL OR chi_tiet_goc.ngay_het_hieu_luc > ngay_ap_dung)

    // 3. Men theo các dây THAM_CHIEU_DEN từ chi_tiet_goc đã được lọc
    OPTIONAL MATCH (chi_tiet_goc)-[:THAM_CHIEU_DEN]->(tham_chieu)

    // 3.1 Lọc luôn thời gian cho các văn bản tham chiếu (Để không lấy phải văn bản tham chiếu đã hết hạn)
    WITH luat_goc, chi_tiet_goc, tham_chieu, ngay_ap_dung
    WHERE tham_chieu IS NULL
      OR (
          (tham_chieu.ngay_hieu_luc IS NULL OR tham_chieu.ngay_hieu_luc <= ngay_ap_dung) AND
          (tham_chieu.ngay_het_hieu_luc IS NULL OR tham_chieu.ngay_het_hieu_luc > ngay_ap_dung)
      )

    // 4. Gom nhóm thành JSON gọn gàng
    WITH luat_goc,
        collect(DISTINCT {id: chi_tiet_goc.id, noi_dung: chi_tiet_goc.noidung}) AS NoiDungChinh,
        collect(DISTINCT {id: tham_chieu.id, noi_dung: tham_chieu.noidung}) AS ThamChieu

    RETURN {
        dieu_luat_ap_dung: luat_goc.id,
        noi_dung_chinh: NoiDungChinh,
        quy_dinh_tham_chieu: ThamChieu
    } AS Context_TraLoi
    """

    print("[Cypher] Đang truy vấn Database...")

    try:
        # Truyền tham số an toàn vào Neo4j (Ngăn chặn Cypher Injection)
        records, _, _ = driver.execute_query(
            cypher_query,
            danh_sach_id=target_ids,
            target_date=target_date
        )
        return [record["Context_TraLoi"] for record in records]

    except Exception as e:
        return [{"Lỗi Database": str(e)}]

xu_phat_vi_pham_description = {
    "type": "function",
    "function": {
        "name": "xu_phat_vi_pham",
        "description": "Tra cứu các quy định về xử phạt vi phạm hành chính trong lĩnh vực hôn nhân gia đình (tảo hôn, vi phạm chế độ một vợ một chồng, v.v.).",
        "parameters": {
            "type": "object",
            "properties": {
                "query": {
                    "type": "string",
                    "description": "Câu hỏi cụ thể của người dùng"
                }
            },
            "required": ["query"],
        },
    },
}

def xu_phat_vi_pham(query: str):
    """
    Tool xử lý tra cứu xử phạt hành chính dựa trên Nghị định 109/2026/NĐ-CP.
    """
    print(f"[Agent xu_phat_vi_pham] Đang xử lý: '{query}'...")

    penalty_schema = """
    Thuộc tính của node (properties):
    DieuKhoanLuat {id: STRING, chuong: STRING, dieu: STRING, khoan: STRING, noidung: STRING}
    DieuLuat {id: STRING, chuong: STRING, dieu: STRING, noidung: STRING}
    DieuKhoanDiemLuat {id: STRING, chuong: STRING, dieu: STRING, khoan: STRING, noidung: STRING, diem: STRING}

    Các mối quan hệ (The relationships):
    (:DieuKhoanLuat)-[:CO_DIEM]->(:DieuKhoanDiemLuat)
    (:DieuLuat)-[:CO_KHOAN]->(:DieuKhoanLuat)

    Các node căn cứ pháp luật cần truy vấn: ["NghiDinh_109_2026_ND_CP_Dieu_61", "NghiDinh_109_2026_ND_CP_Dieu_62"]
    Thông tin về các node căn cứ pháp luật:
    NghiDinh_109_2026_ND_CP_Dieu_61: Xử phạt hành vi tảo hôn, tổ chức tảo hôn.
    NghiDinh_109_2026_ND_CP_Dieu_62: Xử phạt hành vi vi phạm quy định về kết hôn, ly hôn và vi phạm chế độ hôn nhân một vợ, một chồng.
    """

    penalty_examples = """
    Câu hỏi: Tôi kết hôn với chị họ thì bị phạt thế nào?
    Suy luận: Hành vi này vi phạm chế độ hôn nhân và các trường hợp cấm kết hôn. Theo danh sách ID, \"NghiDinh_109_2026_ND_CP_Dieu_62\" là node phù hợp nhất.
    Query Cypher:
    MATCH (luat_goc:DieuLuat {id: "NghiDinh_109_2026_ND_CP_Dieu_62"})
    OPTIONAL MATCH (luat_goc)-[:CO_KHOAN|CO_DIEM*0..2]->(chi_tiet_goc)
    WITH luat_goc, collect(DISTINCT {id: chi_tiet_goc.id, noi_dung: chi_tiet_goc.noidung}) AS NoiDungDieuLuatChinh
    RETURN {
        dieu_luat_ap_dung: luat_goc.id,
        noi_dung_chinh: NoiDungDieuLuatChinh
    } AS Context_TraLoi
    """

    t2c = Text2Cypher(driver)
    t2c.set_prompt_section("schema", penalty_schema)
    t2c.set_prompt_section("examples", penalty_examples)
    t2c.set_prompt_section("question", query)

    cypher = t2c.generate_cypher()
    print(f"[Agent xu_phat_vi_pham] Cypher: {cypher}")

    try:
        records, _, _ = driver.execute_query(cypher)
        return [record.data() for record in records]
    except Exception as e:
        return [f"Lỗi: {e}"]

dang_ky_ket_hon_description = {
    "type": "function",
    "function": {
        "name": "dang_ky_ket_hon",
        "description": "Lấy thông tin quy định về đăng ký kết hôn như kết hôn lại, thẩm quyền đăng ký kết hôn, thủ tục đăng ký kết hôn hay xử lý đăng ký kết hôn không đúng thẩm quyền.",
        "parameters": {
            "type": "object",
            "properties": {
                "query": {
                    "type": "string",
                    "description": "Câu hỏi cụ thể của người dùng."
                }
            },
            "required": ["query"],
        },
    },
}

def dang_ky_ket_hon(query: str):
    """
    Tool xử lý các vấn đề về đăng ký kết hôn và thẩm quyền thực hiện.
    """
    print(f"[Agent dang_ky_ket_hon] Đang xử lý: '{query}'...")

    registration_schema = """
    Thuộc tính của node (properties):
    DieuKhoanLuat {id: STRING, chuong: STRING, dieu: STRING, khoan: STRING, noidung: STRING}
    DieuLuat {id: STRING, chuong: STRING, dieu: STRING, noidung: STRING}
    DieuKhoanDiemLuat {id: STRING, chuong: STRING, dieu: STRING, khoan: STRING, noidung: STRING, diem: STRING}

    Các mối quan hệ (The relationships):
    (:DieuKhoanLuat)-[:CO_DIEM]->(:DieuKhoanDiemLuat)
    (:DieuLuat)-[:CO_KHOAN]->(:DieuKhoanLuat)
    (:DieuLuat)-[:KET_HON_CO_YEU_TO_NUOC_NGOAI]->(:DieuLuat)
    (:DieuLuat)-[:KET_HON_KHONG_CO_YEU_TO_NUOC_NGOAI]->(:DieuLuat)
    (:DieuLuat)-[:KET_HON_KHONG_CO_YEU_TO_NUOC_NGOAI]->(:DieuKhoanLuat)

    Các node căn cứ pháp luật cần truy vấn: ["Dieu_9", "Dieu_13"]
    Thông tin về các node căn cứ pháp luật:
    Dieu_9: Đăng ký kết hôn (Quy định chung, thẩm quyền đăng ký kết hôn, thủ tục đăng ký kết hôn)
    Dieu_13: Xử lý việc đăng ký kết hôn không đúng thẩm quyền
    """

    registration_examples = """
    Câu hỏi: Kết hôn chồng cũ có được không?
    Cypher Query:
    // 1. Chọn node quy định chung
    MATCH (luat_goc:DieuLuat {id: "Dieu_9"})

    // 2. Quét dọc (Top-Down) để lấy trọn vẹn nội dung của Điều 9 (bao gồm Khoản và Điểm)
    OPTIONAL MATCH (luat_goc)-[:CO_KHOAN|CO_DIEM*0..2]->(chi_tiet_goc)

    // 3. Gom nhóm và trả về JSON gọn gàng
    WITH luat_goc,
    collect(DISTINCT {id: chi_tiet_goc.id, noi_dung: chi_tiet_goc.noidung}) AS NoiDungDieuLuat

    RETURN {
      dieu_luat_ap_dung: luat_goc.id,
      noi_dung_chinh: NoiDungDieuLuat
    } AS Context_TraLoi

    Câu hỏi: Kết hôn chồng cũ có được không và thủ tục như thế nào?
    // 1. Lấy node gốc Điều 9 (Quy định về việc đăng ký kết hôn lại)
    MATCH (luat_goc:DieuLuat {id: "Dieu_9"})

    // 2. Vét cạn chi tiết nội dung Điều 9 (Khoản, Điểm)
    OPTIONAL MATCH (luat_goc)-[:CO_KHOAN|CO_DIEM*0..2]->(chi_tiet_goc)

    // 3. Lấy thủ tục: Dùng KET_HON_KHONG_CO_YEU_TO_NUOC_NGOAI (vì câu hỏi không nói rõ có yếu tố nước ngoài hay không nên mặc định là kết hôn trong nước)
    OPTIONAL MATCH (luat_goc)-[:KET_HON_KHONG_CO_YEU_TO_NUOC_NGOAI]->(luat_thu_tuc)

    // 4. Vét cạn chi tiết các điều luật về thủ tục vừa tìm được
    OPTIONAL MATCH (luat_thu_tuc)-[:CO_KHOAN|CO_DIEM*0..2]->(chi_tiet_thu_tuc)

    // 5. Gom nhóm tách bạch giữa luật gốc và luật thủ tục
    WITH luat_goc,
        collect(DISTINCT {id: chi_tiet_goc.id, noi_dung: chi_tiet_goc.noidung}) AS NoiDungDieu9,
        collect(DISTINCT {id: chi_tiet_thu_tuc.id, noi_dung: chi_tiet_thu_tuc.noidung}) AS NoiDungThuTucTrongNuoc

    // 6. Đóng gói gọn gàng thành 1 object JSON trả về cho Agent
    RETURN {
        dieu_luat_goc: luat_goc.id,
        noi_dung_chinh: NoiDungDieu9,
        cac_quy_dinh_thu_tuc: NoiDungThuTucTrongNuoc
    } AS Context_TraLoi

    Câu hỏi: Chồng tôi là người nước ngoài, vậy khi tôi muốn đăng ký kết hôn thì thủ tục như thế nào ạ?
    Cypher Query:
    MATCH (luat_goc:DieuLuat {id: "Dieu_9"})
    OPTIONAL MATCH (luat_goc)-[:CO_KHOAN|CO_DIEM*0..2]->(chi_tiet_goc)
    OPTIONAL MATCH (luat_goc)-[:KET_HON_CO_YEU_TO_NUOC_NGOAI]->(luat_lien_quan)
    OPTIONAL MATCH (luat_lien_quan)-[:CO_KHOAN|CO_DIEM*0..2]->(chi_tiet_lien_quan)
    WITH luat_goc,
         collect(DISTINCT {id: chi_tiet_goc.id, noi_dung: chi_tiet_goc.noidung}) AS NoiDungDieu9,
         collect(DISTINCT {id: chi_tiet_lien_quan.id, noi_dung: chi_tiet_lien_quan.noidung}) AS NoiDungLienQuanNuocNgoai
    RETURN { dieu_luat_goc: luat_goc.id, noi_dung_chinh: NoiDungDieu9, cac_quy_dinh_yeu_to_nuoc_ngoai: NoiDungLienQuanNuocNgoai } AS Context_TraLoi

    Câu hỏi: Tôi kết hôn với người trong nước nhưng đăng ký kết hôn sai thẩm quyền thì sao
    Cypher Query:
    MATCH (luat_goc:DieuLuat {id: "Dieu_13"})
    OPTIONAL MATCH (luat_goc)-[:CO_KHOAN|CO_DIEM*0..2]->(chi_tiet_goc)
    OPTIONAL MATCH (luat_goc)-[:KET_HON_KHONG_CO_YEU_TO_NUOC_NGOAI]->(luat_lien_quan)
    OPTIONAL MATCH (luat_lien_quan)-[:CO_KHOAN|CO_DIEM*0..2]->(chi_tiet_lien_quan)
    WITH luat_goc,
         collect(DISTINCT {id: chi_tiet_goc.id, noi_dung: chi_tiet_goc.noidung}) AS NoiDungDieu13,
         collect(DISTINCT {id: chi_tiet_lien_quan.id, noi_dung: chi_tiet_lien_quan.noidung}) AS NoiDungLienQuanTrongNuoc
    RETURN { dieu_luat_goc: luat_goc.id, noi_dung_chinh: NoiDungDieu13, cac_quy_dinh_trong_nuoc: NoiDungLienQuanTrongNuoc } AS Context_TraLoi
    """

    t2c = Text2Cypher(driver)
    t2c.set_prompt_section("schema", registration_schema)
    t2c.set_prompt_section("examples", registration_examples)
    t2c.set_prompt_section("question", query)

    cypher = t2c.generate_cypher()
    print(f"[Agent dang_ky_ket_hon] Cypher: {cypher}")

    try:
        records, _, _ = driver.execute_query(cypher)
        return [record.data() for record in records]
    except Exception as e:
        return [f"Lỗi: {e}"]

chung_song_nhu_vo_chong_description = {
    "type": "function",
    "function": {
        "name": "chung_song_nhu_vo_chong",
        "description": "Lấy thông tin quy định về Giải quyết hậu quả; Xác định quyền, nghĩa vụ của cha mẹ và con và Giải quyết quan hệ tài sản, nghĩa vụ và hợp đồng trong trường hợp nam, nữ chung sống với nhau như vợ chồng mà không đăng ký kết hôn.",
        "parameters": {
            "type": "object",
            "properties": {
                "query": {
                    "type": "string",
                    "description": "Câu hỏi cụ thể của người dùng."
                }
            },
            "required": ["query"],
        },
    },
}

def chung_song_nhu_vo_chong(query: str):
    """
    Tool xử lý các vấn đề về nam nữ chung sống như vợ chồng mà không đăng ký kết hôn.
    """
    print(f"[Agent chung_song_nhu_vo_chong] Đang xử lý: '{query}'...")

    schema_cohabitation = """
    Thuộc tính của node (properties):
    DieuKhoanLuat {id: STRING, chuong: STRING, dieu: STRING, khoan: STRING, noidung: STRING}
    DieuLuat {id: STRING, chuong: STRING, dieu: STRING, noidung: STRING}
    DieuKhoanDiemLuat {id: STRING, chuong: STRING, dieu: STRING, khoan: STRING, noidung: STRING, diem: STRING}

    Các mối quan hệ (The relationships):
    (:DieuKhoanLuat)-[:CO_DIEM]->(:DieuKhoanDiemLuat)
    (:DieuLuat)-[:CO_KHOAN]->(:DieuKhoanLuat)

    Các node căn cứ pháp luật cần truy vấn: [\"Dieu_14\", \"Dieu_15\", \"Dieu_16\"]
    Thông tin về các node căn cứ pháp luật:
    Dieu_14: Giải quyết hậu quả của việc nam, nữ chung sống với nhau như vợ chồng mà không đăng ký kết hôn
    Dieu_15: Quyền, nghĩa vụ của cha mẹ và con trong trường hợp nam, nữ chung sống với nhau như vợ chồng mà không đăng ký kết hôn
    Dieu_16: Giải quyết quan hệ tài sản, nghĩa vụ và hợp đồng của nam, nữ chung sống với nhau như vợ chồng mà không đăng ký kết hôn
    """

    examples_cohabitation = """
    Câu hỏi: Nam nữ chung sống như vợ chồng mà không đăng ký kết hôn thì có làm phát sinh quyền nghĩa vụ giữa vợ và chồng không?
    Cypher query:
    MATCH (luat_goc:DieuLuat {id: "Dieu_14"})
    OPTIONAL MATCH (luat_goc)-[:CO_KHOAN|CO_DIEM*0..2]->(chi_tiet_goc)
    OPTIONAL MATCH (chi_tiet_goc)-[:THAM_CHIEU_DEN]-(luat_tham_chieu)
    OPTIONAL MATCH (luat_tham_chieu)-[:CO_KHOAN|CO_DIEM*0..2]->(chi_tiet_tham_chieu)
    WITH luat_goc,
         collect(DISTINCT {id: chi_tiet_goc.id, noi_dung: chi_tiet_goc.noidung}) AS NoiDungDieu14,
         collect(DISTINCT {id: chi_tiet_tham_chieu.id, noi_dung: chi_tiet_tham_chieu.noidung}) AS NoiDungThamChieu
    RETURN {
        dieu_luat_goc: luat_goc.id,
        noi_dung_chinh: NoiDungDieu14,
        cac_quy_dinh_tham_chieu: NoiDungThamChieu
    } AS Context_TraLoi
    """

    t2c = Text2Cypher(driver)
    t2c.set_prompt_section("schema", schema_cohabitation)
    t2c.set_prompt_section("examples", examples_cohabitation)
    t2c.set_prompt_section("question", query)

    cypher = t2c.generate_cypher()
    print(f"[Agent chung_song_nhu_vo_chong] Cypher: {cypher}")

    try:
        records, _, _ = driver.execute_query(cypher)
        return [record.data() for record in records]
    except Exception as e:
        return [f"Lỗi: {e}"]

# movies_info_by_actor_description = {
#     "type": "function",
#     "function": {
#         "name": "movies_info_by_actor",
#         "description": "Lấy thông tin về một bộ phim thông qua việc cung cấp tên diễn viên.",
#         "parameters": {
#             "type": "object",
#             "properties": {
#                 "actor": {
#                     "type": "string",
#                     "description": "Tên diễn viên",
#                 }
#             },
#             "required": ["actor"],
#         },
#     },
# }

# def movies_info_by_actor(actor: str):
#     query = """
#     MATCH (a:Person)-[:ACTED_IN]->(m:Movie)
#     OPTIONAL MATCH (m)<-[:ACTED_IN]-(a:Person)
#     OPTIONAL MATCH (m)<-[:DIRECTED]-(d:Person)
#     WHERE toLower(a.name) CONTAINS $actor
#     RETURN m AS movie, collect(a.name) AS cast, collect(d.name) AS directors
#     """
#     records, _, _ = driver.execute_query(query, actor=actor.lower())
#     return [record.data() for record in records]

tools = {
    "dieu_kien_ket_hon": {
        "description": dieu_kien_ket_hon_description,
        "function": dieu_kien_ket_hon
    },
    "dang_ky_ket_hon": {
        "description": dang_ky_ket_hon_description,
        "function": dang_ky_ket_hon
    },
    "ket_hon_trai_phap_luat": {
        "description": ket_hon_trai_phap_luat_description,
        "function": ket_hon_trai_phap_luat
    },
    "chung_song_nhu_vo_chong": {
        "description": chung_song_nhu_vo_chong_description,
        "function": chung_song_nhu_vo_chong
    },
    "xu_phat_vi_pham": {
        "description": xu_phat_vi_pham_description,
        "function": xu_phat_vi_pham
    },
    "text2cypher": {
        "description": text2cypher_description,
        "function": text2cypher
    },
    "respond": {
        "description": answer_given_description,
        "function": answer_given
    }
}

# Cập nhật danh sách tools để bao gồm tool mới
# tools["ket_hon_trai_phap_luat"] = {
#     "description": ket_hon_trai_phap_luat_description,
#     "function": ket_hon_trai_phap_luat
# }

# ==========================================
# TOOL ROUTER AGENT
# ==========================================
tool_picker_prompt = tool_picker_prompt = """
Bạn là một hệ thống định tuyến (Router Agent) thông minh.
Nhiệm vụ của bạn là đọc câu hỏi của người dùng và chọn ĐÚNG và ĐỦ các công cụ (tools) để giải quyết TOÀN BỘ câu hỏi.

QUY TẮC BẮT BUỘC (CRITICAL RULES):
1. PHÂN TÍCH NHIỀU Ý: Người dùng thường hỏi nhiều vấn đề trong cùng 1 câu. Bạn PHẢI bóc tách từng vế của câu hỏi.
2. Tùy vào câu hỏi có thể cần phải gọi nhiều tool khác nhau. Nhưng không gọi cùng 1 tool nhiều lần.
3. ĐIỀN ĐỦ THAM SỐ: Đảm bảo tham số `query` chứa nguyên văn ý hỏi của người dùng cho công cụ đó.

Ví dụ tư duy:
- Câu hỏi: "Tôi là nam năm nay 18 tuổi thì có được kết hôn không? Và tôi có quyền được yêu cầu hủy kết hôn trái pháp luật của bố mẹ tôi không?"
- Ý 1: Hỏi về độ tuổi kết hôn (Nam 18 tuổi) -> Dùng công cụ `dieu_kien_ket_hon`
- Ý 2: Hỏi về quyền yêu cầu hủy kết hôn trái pháp luật -> Dùng công cụ `ket_hon_trai_phap_luat`
=> BẠN PHẢI GỌI CẢ 2 CÔNG CỤ NÀY.
"""

def handle_tool_calls(tools: dict[str, any], llm_tool_calls: list[dict[str, any]], updated_question):
    output = []
    called_tools = set()
    if llm_tool_calls:
        print('llm_tool_calls:', llm_tool_calls)
        for tool_call in llm_tool_calls:
            tool_name = tool_call['name']

            # 🚨 skip nếu tool đã gọi rồi
            if tool_name in called_tools:
                continue

            called_tools.add(tool_name)

            function_to_call = tools[tool_call['name']]["function"]
            # 🚨 Override args từ updater
            function_args = {
                "query": updated_question
            } if updated_question else tool_call.get("args", {})
            res = function_to_call(**function_args)
            output.append(res)
    return output

def tool_choice(messages, temperature=0, tools=[], config={}, model=None):
    llm = ChatGroq(api_key=GROQ_API_KEY, model="openai/gpt-oss-120b", temperature=0, max_tokens=2048)
    # Ràng buộc tools vào mô hình Groq
    llm_with_tools = llm.bind_tools(tools)
    return llm_with_tools.invoke(messages).tool_calls

def route_question(question: str, tools: dict[str, any], answers: list[dict[str, str]]):
    llm_tool_calls = tool_choice(
        [
            {
                "role": "system",
                "content": tool_picker_prompt,
            },
            *answers,
            {
                "role": "user",
                "content": f"Câu hỏi của người dùng cần tìm công cụ để giải quyết: '{question}'",
            },
        ],
        tools=[tool["description"] for tool in tools.values()],
    )
    return handle_tool_calls(tools, llm_tool_calls, question)

# import json

# # 1. Định nghĩa các nhóm Tool
# TOOL_GROUPS = {
#     "marriage": {
#         "description": "Các vấn đề về kết hôn, độ tuổi, điều kiện và thủ tục đăng ký kết hôn.",
#         "tools": ["dieu_kien_ket_hon"]
#     },
#     "general": {
#         "description": "Các câu hỏi chung hoặc không thuộc các nhóm cụ thể trên.",
#         "tools": ["text2cypher", "respond"]
#     }
# }

# # 2. Agent phân loại chủ đề (Category Router)
# CATEGORY_ROUTER_PROMPT = """
# Bạn là một chuyên gia phân loại câu hỏi pháp luật.
# Dựa vào câu hỏi của người dùng, hãy xác định nó thuộc nhóm nào trong danh sách sau:
# {groups_description}

# Chỉ trả về JSON theo định dạng:
# {{
#     "category": "tên_nhóm"
# }}
# """

# def get_category(question: str) -> str:
#     groups_desc = "\n".join([f"- {name}: {info['description']}" for name, info in TOOL_GROUPS.items()])
#     messages = [
#         {"role": "system", "content": CATEGORY_ROUTER_PROMPT.format(groups_description=groups_desc)},
#         {"role": "user", "content": f"Câu hỏi: '{question}'"}
#     ]
#     output = chat(messages)
#     try:
#         res = json.loads(strip_code_fences(output))
#         return res.get("category", "general")
#     except:
#         return "general"

# # 3. Cập nhật hàm route_question để hỗ trợ phân cấp
# def route_question_hierarchical(question: str, all_tools: dict[str, any], history: list):
#     # Bước A: Xác định nhóm chủ đề
#     category = get_category(question)
#     print(f"[Router] Chủ đề xác định: {category}")

#     # Bước B: Lấy danh sách tools tương ứng
#     target_tool_names = TOOL_GROUPS.get(category, TOOL_GROUPS["general"])["tools"]
#     # Luôn bao gồm 'respond' để agent có thể trả lời nếu cần
#     if "respond" not in target_tool_names: target_tool_names.append("respond")

#     selected_tools_desc = [
#         all_tools[name]["description"] for name in target_tool_names if name in all_tools
#     ]

#     # Bước C: Gọi Tool Choice với danh sách tool đã được lọc
#     llm_tool_calls = tool_choice(
#         [
#             {"role": "system", "content": tool_picker_prompt},
#             *history,
#             {"role": "user", "content": f"Câu hỏi cần giải quyết: '{question}'"},
#         ],
#         tools=selected_tools_desc,
#     )

#     return handle_tool_calls(all_tools, llm_tool_calls)

"""Bây giờ, chúng ta sẽ cập nhật lại hàm `main` để sử dụng `route_question_hierarchical` thay vì hàm cũ."""

# def main_hierarchical(input: str, session_history: list):
#     print("\n" + "="*50)

#     updated_question = query_update(input, session_history)

#     # Sử dụng Router phân cấp ở đây
#     tool_response = route_question_hierarchical(updated_question, tools, session_history)

#     current_context = list(session_history)
#     current_context.append({
#         "role": "system",
#         "content": f"Dữ liệu lấy được: {json.dumps(tool_response, ensure_ascii=False)}"
#     })

#     critique = critique_answers(input, current_context)

#     if critique:
#         print(f"[Critic] Đang bổ sung thông tin: {critique}")
#         combined_sub = " ".join(critique)
#         additional_res = route_question_hierarchical(combined_sub, tools, current_context)
#         current_context.append({
#             "role": "system",
#             "content": f"Dữ liệu bổ sung: {json.dumps(additional_res, ensure_ascii=False)}"
#         })

#     llm_response = chat([
#         {"role": "system", "content": main_prompt},
#         *current_context,
#         {"role": "user", "content": input},
#     ])

#     session_history.append({"role": "user", "content": input})
#     session_history.append({"role": "assistant", "content": llm_response})
#     return llm_response

#####################
# Query updater (Cập nhật câu hỏi)
#####################

query_update_prompt = """
    Bạn là một chuyên gia trong việc tinh chỉnh câu hỏi pháp luật.
    Nhiệm vụ của bạn là bổ sung thông tin ngữ cảnh từ lịch sử trò chuyện vào câu hỏi hiện tại để nó trở nên rõ ràng và đầy đủ thông tin nhất.

    QUY TẮC QUAN TRỌNG:
    1. BẮT BUỘC giữ lại TOÀN BỘ các ý định/vấn đề mà người dùng đang hỏi. Nếu người dùng hỏi 2-3 vấn đề khác nhau trong một câu, bạn phải giữ nguyên số lượng vấn đề đó.
    2. Không được tự ý lược bỏ bất kỳ ý nào để làm câu hỏi ngắn gọn hơn.
    3. Chỉ chỉnh sửa để câu hỏi rõ nghĩa hơn (ví dụ: thay thế đại từ 'họ', 'nó' bằng danh từ cụ thể từ lịch sử).

    Định dạng JSON bắt buộc:
    {
        "question": "câu_hỏi_đầy_đủ_giữ_nguyên_mọi_ý_định"
    }
"""

def query_update(input: str, answers: list[any]) -> str:
    messages = [
        {"role": "system", "content": query_update_prompt},
        *answers,
        {"role": "user", "content": f"Hãy tinh chỉnh câu hỏi này nhưng phải giữ trọn vẹn mọi ý định: '{input}'"},
    ]
    output = chat(messages)
    try:
        jsonloads = json.loads(strip_code_fences(output))
        print('1 (Query Update - Đã sửa):', jsonloads)
        return jsonloads["question"]
    except:
        return input

#############
# Critic (Đánh giá câu trả lời)
#############
answer_critique_prompt = """
    Bạn là một chuyên gia trong việc xác định xem các câu hỏi đã được trả lời đầy đủ chưa hay liệu có cơ hội nào để làm phong phú thêm câu trả lời.
    Người dùng sẽ cung cấp một câu hỏi, và bạn sẽ rà soát các thông tin dữ liệu được cung cấp để xem câu hỏi đó đã được giải đáp hay chưa.
    Nếu có bất kỳ thông tin nào bị thiếu trong câu trả lời, bạn sẽ đề xuất một tập hợp các câu hỏi mới có thể được dùng để thu thập phần thông tin còn thiếu đó.
    Tất cả các câu hỏi phụ mới này phải hoàn chỉnh, mang tính nguyên tử và cụ thể.
    Tuy nhiên, nếu thông tin được cung cấp ĐÃ ĐỦ để trả lời câu hỏi ban đầu, bạn BẮT BUỘC phải phản hồi bằng một danh sách rỗng.

    Định dạng JSON cần sử dụng để tìm kiếm thông tin còn thiếu:
    {
        "questions": ["câu_hỏi_1", "câu_hỏi_2"]
    }
"""

def critique_answers(question: str, answers: list[dict[str, str]]) -> list[str]:
    messages = [
        {
            "role": "system",
            "content": answer_critique_prompt,
        },
        *answers,
        {
            "role": "user",
            "content": f"Câu hỏi gốc của người dùng cần trả lời: {question}",
        },
    ]
    output = chat(messages=messages)
    try:
        cleaned_output = strip_code_fences(output)
        if not cleaned_output:
            return []
        jsonloads = json.loads(cleaned_output)
        print('2 (Critic):', jsonloads)
        return jsonloads.get("questions", [])
    except (json.JSONDecodeError, Exception) as e:
        print(f"Lỗi giải mã JSON 2: {e}")
        return []

# # ###############
# # # Main function (Luồng chính)
# # ###############

# main_prompt = """
#     Nhiệm vụ của bạn là giúp người dùng giải đáp các câu hỏi của họ BẰNG TIẾNG VIỆT.
#     Bạn sẽ nhận được các câu hỏi của người dùng và các thông tin (ngữ cảnh) cần thiết để trả lời những câu hỏi đó.
#     Nếu thiếu thông tin để trả lời một phần hoặc toàn bộ câu hỏi, bạn phải nói rõ rằng thông tin đó bị thiếu. Bạn BẮT BUỘC chỉ được sử dụng các thông tin được cung cấp trong prompt để trả lời các câu hỏi.
#     Tuyệt đối không được bịa đặt thông tin hay sử dụng kiến thức bên ngoài.
# """

# # def main(input: str):
# #     answers = handle_user_input(input)
# #     critique = critique_answers(input, answers)

# #     if critique:
# #         answers = handle_user_input(" ".join(critique), answers)

# #     llm_response = chat(
# #         [
# #             {"role": "system", "content": main_prompt},
# #             *answers,
# #             {"role": "user", "content": f"Câu hỏi của người dùng cần được giải đáp: {input}"},
# #         ]
# #     )

# #     return llm_response
# import time

# def main(input: str):
#     print("\n" + "="*50)
#     print(f"BẮT ĐẦU XỬ LÝ CÂU HỎI: {input}")

#     # 1. Đo thời gian Xử lý đầu vào & Gọi Tool
#     t0 = time.time()
#     answers = handle_user_input(input)
#     t1 = time.time()
#     print(f"⏱️ [Bước 1] Query Update & Gọi Tool mất: {t1 - t0:.2f} giây")

#     # # 2. Đo thời gian Critic đánh giá
#     # critique = critique_answers(input, answers)
#     # t2 = time.time()
#     # print(f"⏱️ [Bước 2] Critic đánh giá mất: {t2 - t1:.2f} giây")

#     # # 3. Đo thời gian Vòng lặp (Nếu có)
#     # if critique:
#     #     print(f"⚠️ Critic yêu cầu làm rõ: {critique}")
#     #     answers = handle_user_input(" ".join(critique), answers)
#     # t3 = time.time()
#     # if critique:
#     #     print(f"⏱️ [Bước 3] Xử lý thêm theo yêu cầu Critic mất: {t3 - t2:.2f} giây")

#     t3=t1

#     # 4. Đo thời gian Sinh câu trả lời cuối
#     llm_response = chat(
#         [
#             {"role": "system", "content": main_prompt},
#             *answers,
#             {"role": "user", "content": f"Câu hỏi của người dùng cần được giải đáp: {input}"},
#         ]
#     )
#     t4 = time.time()
#     print(f"⏱️ [Bước 4] Tổng hợp câu trả lời cuối mất: {t4 - t3:.2f} giây")
#     print(f"🚀 TỔNG THỜI GIAN: {t4 - t0:.2f} giây")
#     print("="*50 + "\n")

#     answers.append({"role": "assistant", "content": llm_response})
#     return llm_response

# Main function (Luồng chính có bộ nhớ)

main_prompt = """
    Nhiệm vụ của bạn là giúp người dùng giải đáp các câu hỏi của họ BẰNG TIẾNG VIỆT.
    Bạn sẽ nhận được các câu hỏi của người dùng và các thông tin (ngữ cảnh) lấy từ cơ sở dữ liệu để trả lời.

    QUY TẮC PHẢN HỒI:
    1. LUÔN LUÔN trích dẫn rõ ràng TẤT CẢ tên Điều, Khoản, Điểm và nội dung của luật được sử dụng làm căn cứ trong câu trả lời (từ các node DieuLuat, DieuKhoanLuat, DieuKhoanDiemLuat) TRƯỚC KHI đưa ra lời giải thích hoặc câu trả lời.
    3. Tuyệt đối không được bịa đặt thông tin pháp luật không có trong ngữ cảnh được cung cấp.
    4. Trình bày câu trả lời chuyên nghiệp, dễ hiểu.
"""

def main(input: str, session_history: list):
    print("\n" + "="*50)

    # 1. Cập nhật câu hỏi dựa trên lịch sử
    updated_question = query_update(input, session_history)

    # 2. Lấy dữ liệu lần 1
    tool_response = route_question(updated_question, tools, session_history)

    current_context = list(session_history)
    current_context.append({
        "role": "system",
        "content": f"Dữ liệu lấy được từ hệ thống cho câu hỏi '{updated_question}': {json.dumps(tool_response, ensure_ascii=False)}"
    })

    # # 3. Agent Critic kiểm tra tính đầy đủ
    # critique = critique_answers(input, current_context)

    # # 4. Nếu thiếu thông tin, thực hiện truy vấn bổ sung
    # if critique:
    #     print(f"[Critic] Phát hiện thiếu thông tin, đang tìm thêm: {critique}")
    #     combined_sub_questions = " ".join(critique)
    #     additional_tool_response = route_question(combined_sub_questions, tools, current_context)

    #     current_context.append({
    #         "role": "system",
    #         "content": f"Dữ liệu bổ sung lấy được cho các vấn đề '{combined_sub_questions}': {json.dumps(additional_tool_response, ensure_ascii=False)}"
    #     })

    # 5. Sinh câu trả lời cuối cùng
    llm_response = chat(
        [
            {"role": "system", "content": main_prompt},
            *current_context,
            {"role": "user", "content": f"Câu hỏi của người dùng: {input}"},
        ]
    )

    session_history.append({"role": "user", "content": input})
    session_history.append({"role": "assistant", "content": llm_response})

    print(f"Xử lý xong!")
    print("="*50 + "\n")
    return llm_response

my_chat_history = []

# Question 1
print("USER: Xử lý việc kết hôn trái pháp luật như thế nào?")
response_1 = main("Xử lý việc kết hôn trái pháp luật như thế nào?"
, my_chat_history)
print("\n BOT:", response_1)
print("-" * 50)

# # Question 2
# print("USER: Nếu ra tòa thì cha mẹ cháu bé sẽ có thể bị phạt như thế nào?")
# response_2 = main("Nếu ra tòa thì cha mẹ cháu bé sẽ có thể bị phạt như thế nào?", my_chat_history)
# print("\n BOT:", response_2)
# print("-" * 50)

"""### Cài đặt thư viện bổ sung cho LangGraph"""

# !pip install langgraph

"""### Ví dụ tích hợp Memory và LangGraph

Đoạn code này mô phỏng cách LangGraph lưu trữ trạng thái vào SQLite và cách sử dụng logic tóm tắt.
"""

# from typing import Annotated, TypedDict
# from langgraph.graph import StateGraph, START, END
# from langgraph.graph.message import add_messages
# from langgraph.checkpoint.memory import MemorySaver
# from langchain_core.messages import SystemMessage, HumanMessage, AIMessage

# # 1. Định nghĩa trạng thái của Graph
# class State(TypedDict):
#     # add_messages giúp cộng dồn tin nhắn mới vào lịch sử
#     messages: Annotated[list, add_messages]
#     summary: str

# # 2. Khởi tạo bộ nhớ tạm (Checkpointer)
# # Trong thực tế bạn dùng SqliteSaver để lưu vào file .db
# memory = MemorySaver()

# # 3. Logic xử lý Node
# def call_model(state: State):
#     # Giả sử đây là nơi bạn gọi LLM
#     # Nếu state['summary'] có nội dung, hãy đưa nó vào prompt
#     system_prompt = f"Tóm tắt nội dung cũ: {state.get('summary', '')}"
#     messages = [SystemMessage(content=system_prompt)] + state["messages"]

#     # Gọi LLM (ở đây giả lập response)
#     response = AIMessage(content="Đây là câu trả lời từ Agent!")
#     return {"messages": [response]}

# # 4. Logic tóm tắt (Summary Node)
# def summarize_conversation(state: State):
#     # Nếu số lượng tin nhắn > 6, ta tiến hành tóm tắt
#     if len(state["messages"]) > 6:
#         # Gọi LLM để tóm tắt state['messages']
#         new_summary = "LLM đã tóm tắt các nội dung cũ tại đây..."
#         # Giữ lại 2 tin nhắn cuối, xóa các tin nhắn cũ đã tóm tắt
#         delete_messages = [m.id for m in state["messages"][:-2]]
#         return {"summary": new_summary, "messages": delete_messages}
#     return {}

# # 5. Xây dựng Graph
# workflow = StateGraph(State)
# workflow.add_node("agent", call_model)
# workflow.add_node("summarize", summarize_conversation)

# workflow.add_edge(START, "agent")
# workflow.add_edge("agent", "summarize")
# workflow.add_edge("summarize", END)

# # Biên dịch graph với checkpointer
# app = workflow.compile(checkpointer=memory)

# # 6. Chạy thử với một session_id cụ thể
# config = {"configurable": {"thread_id": "user_abc_123"}}
# input_msg = {"messages": [HumanMessage(content="Chào bạn, tôi muốn hỏi về luật!")]}

# # Mỗi lần chạy, LangGraph tự load/save vào 'memory' dựa trên thread_id
# # for event in app.stream(input_msg, config):
# #     print(event)

# # Demo
# response = main("Tôi có thể kết hôn không?")
# print(response)

!pip install PyMuPDF

import fitz  # PyMuPDF
import re
from neo4j import GraphDatabase

class NghiDinhGraphBuilder:
    def __init__(self, uri, user, password):
        self.driver = GraphDatabase.driver(uri, auth=(user, password))

        # Tiền tố ID theo yêu cầu
        self.prefix = "NghiDinh_82_2020_ND_CP"

        # Các thuộc tính chung cho mọi node
        self.common_props = {
            "loai_van_ban": "Nghị định",
            "ngay_ban_hanh": "15/07/2020",
            "ngay_co_hieu_luc": "01/09/2020",
            "ngay_het_hieu_luc": "--",
            "tinh_trang_hieu_luc": "Hết hiệu lực một phần",
            "cap_bac_phap_ly": 5
        }

    def close(self):
        self.driver.close()

    def parse_pdf_and_insert(self, pdf_path):
        # 1. Trích xuất text từ PDF
        doc = fitz.open(pdf_path)
        full_text = ""
        for page in doc:
            full_text += page.get_text() + "\n"

        lines = full_text.split('\n')

        articles = []
        clauses = []
        points = []

        # Regex nhận diện
        chuong_pattern = re.compile(r'^Chương\s+([IVXLCDM]+)', re.IGNORECASE)
        dieu_pattern = re.compile(r'^Điều\s+(\d+[a-zA-Z]?)\.\s*(.*)')
        khoan_pattern = re.compile(r'^(\d+)\.\s+(.*)')
        diem_pattern = re.compile(r'^([a-zđ])\)\s+(.*)')

        in_target_range = False
        current_chuong = "Chưa xác định"
        current_dieu_id = None
        current_khoan_id = None

        active_entity = None

        # 2. Phân tích từng dòng
        for line in lines:
            line = line.strip()
            if not line:
                continue

            # Theo dõi Chương
            if chuong_match := chuong_pattern.match(line):
                current_chuong = chuong_match.group(1)
                continue

            # Bật/tắt cờ khi quét đến khoảng Điều 58 - Điều 63
            if dieu_match := dieu_pattern.match(line):
                dieu_num = dieu_match.group(1)
                if int(dieu_num) == 58:
                    in_target_range = True
                elif int(dieu_num) == 64:
                    in_target_range = False
                    break # Đã qua Điều 63, dừng phân tích

            if not in_target_range:
                continue

            # Xử lý khi nằm trong vùng Điều 58 -> 63
            if dieu_match := dieu_pattern.match(line):
                dieu_num = dieu_match.group(1)

                # Cách đặt tên ID theo yêu cầu: NghiDinh_82_2020_ND_CP_Diem_X
                current_dieu_id = f"{self.prefix}_Dieu_{dieu_num}"
                current_khoan_id = None

                art_dict = {
                    "id": current_dieu_id,
                    "chuong": current_chuong,
                    "dieu": dieu_num,
                    "noidung": line
                }
                articles.append(art_dict)
                active_entity = art_dict
                continue

            if khoan_match := khoan_pattern.match(line):
                khoan_num = khoan_match.group(1)
                current_khoan_id = f"{current_dieu_id}_Khoan_{khoan_num}"

                khoan_dict = {
                    "id": current_khoan_id,
                    "chuong": current_chuong,
                    "dieu": dieu_num, # Lấy từ điều hiện tại
                    "khoan": khoan_num,
                    "noidung": line,
                    "dieu_id": current_dieu_id
                }
                clauses.append(khoan_dict)
                active_entity = khoan_dict
                continue

            if diem_match := diem_pattern.match(line):
                diem_char = diem_match.group(1)
                diem_id = f"{current_khoan_id}_Diem_{diem_char}" if current_khoan_id else f"{current_dieu_id}_Diem_{diem_char}"

                diem_dict = {
                    "id": diem_id,
                    "chuong": current_chuong,
                    "dieu": dieu_num,
                    "khoan": khoan_num if current_khoan_id else "",
                    "diem": diem_char,
                    "noidung": line,
                    "khoan_id": current_khoan_id
                }
                points.append(diem_dict)
                active_entity = diem_dict
                continue

            # Cộng dồn nội dung nếu đoạn văn bản bị ngắt dòng trong PDF
            if active_entity is not None:
                active_entity["noidung"] += " " + line

        print(f"Trích xuất: {len(articles)} Điều, {len(clauses)} Khoản, {len(points)} Điểm.")

        # 3. Đẩy vào Neo4j bằng UNWIND + MERGE
        with self.driver.session() as session:
            session.execute_write(self._upsert_articles, articles, self.common_props)
            session.execute_write(self._upsert_clauses, clauses, self.common_props)
            session.execute_write(self._upsert_points, points, self.common_props)

        print("Đã hoàn tất Insert/Upsert vào Neo4j!")

    @staticmethod
    def _upsert_articles(tx, data, props):
        query = """
        UNWIND $data AS row
        MERGE (d:DieuLuat {id: row.id})
        SET d.chuong = row.chuong,
            d.dieu = row.dieu,
            d.noidung = row.noidung,
            d.loai_van_ban = $props.loai_van_ban,
            d.ngay_ban_hanh = $props.ngay_ban_hanh,
            d.ngay_co_hieu_luc = $props.ngay_co_hieu_luc,
            d.ngay_het_hieu_luc = $props.ngay_het_hieu_luc,
            d.tinh_trang_hieu_luc = $props.tinh_trang_hieu_luc,
            d.cap_bac_phap_ly = $props.cap_bac_phap_ly
        """
        tx.run(query, data=data, props=props)

    @staticmethod
    def _upsert_clauses(tx, data, props):
        query = """
        UNWIND $data AS row
        MERGE (k:DieuKhoanLuat {id: row.id})
        SET k.chuong = row.chuong,
            k.dieu = row.dieu,
            k.khoan = row.khoan,
            k.noidung = row.noidung,
            k.loai_van_ban = $props.loai_van_ban,
            k.ngay_ban_hanh = $props.ngay_ban_hanh,
            k.ngay_co_hieu_luc = $props.ngay_co_hieu_luc,
            k.ngay_het_hieu_luc = $props.ngay_het_hieu_luc,
            k.tinh_trang_hieu_luc = $props.tinh_trang_hieu_luc,
            k.cap_bac_phap_ly = $props.cap_bac_phap_ly
        WITH k, row
        MATCH (d:DieuLuat {id: row.dieu_id})
        MERGE (d)-[:CO_KHOAN]->(k)
        """
        tx.run(query, data=data, props=props)

    @staticmethod
    def _upsert_points(tx, data, props):
        query = """
        UNWIND $data AS row
        MERGE (p:DieuKhoanDiemLuat {id: row.id})
        SET p.chuong = row.chuong,
            p.dieu = row.dieu,
            p.khoan = row.khoan,
            p.diem = row.diem,
            p.noidung = row.noidung,
            p.loai_van_ban = $props.loai_van_ban,
            p.ngay_ban_hanh = $props.ngay_ban_hanh,
            p.ngay_co_hieu_luc = $props.ngay_co_hieu_luc,
            p.ngay_het_hieu_luc = $props.ngay_het_hieu_luc,
            p.tinh_trang_hieu_luc = $props.tinh_trang_hieu_luc,
            p.cap_bac_phap_ly = $props.cap_bac_phap_ly
        WITH p, row
        MATCH (k:DieuKhoanLuat {id: row.khoan_id})
        MERGE (k)-[:CO_DIEM]->(p)
        """
        tx.run(query, data=data, props=props)

URI = NEO4J_URI
USER = NEO4J_USERNAME
PASSWORD = NEO4J_PASSWORD

# Bạn truyền đường dẫn file PDF Nghị định vào đây
PDF_FILE_PATH = "/content/Nghị-định-82-2020-NĐ-CP.pdf"

builder = NghiDinhGraphBuilder(URI, USER, PASSWORD)
try:
    builder.parse_pdf_and_insert(PDF_FILE_PATH)
finally:
    builder.close()
