"""Registry các Cypher template cho topic xu_phat_vi_pham."""
from __future__ import annotations

from adapter.cypher_templates import TemplateRegistry

from adapter.cypher_templates.xu_phat_vi_pham.xu_phat_ket_hon_ly_hon_tong_quat import xu_phat_ket_hon_ly_hon_tong_quat
from adapter.cypher_templates.xu_phat_vi_pham.tao_hon_va_to_chuc_tao_hon import tao_hon_va_to_chuc_tao_hon
from adapter.cypher_templates.xu_phat_vi_pham.vi_pham_mot_vo_mot_chong import vi_pham_mot_vo_mot_chong
from adapter.cypher_templates.xu_phat_vi_pham.can_tro_cuong_ep_ket_hon_ly_hon import can_tro_cuong_ep_ket_hon_ly_hon
from adapter.cypher_templates.xu_phat_vi_pham.quan_he_hon_nhan_bi_cam_vphc import quan_he_hon_nhan_bi_cam_vphc
from adapter.cypher_templates.xu_phat_vi_pham.toi_loan_luan_hinh_su import toi_loan_luan_hinh_su
from adapter.cypher_templates.xu_phat_vi_pham.ket_hon_ly_hon_gia_tao import ket_hon_ly_hon_gia_tao
from adapter.cypher_templates.xu_phat_vi_pham.sinh_con_mang_thai_ho_thuong_mai import sinh_con_mang_thai_ho_thuong_mai
from adapter.cypher_templates.xu_phat_vi_pham.vi_pham_giam_ho import vi_pham_giam_ho
from adapter.cypher_templates.xu_phat_vi_pham.vi_pham_nuoi_con_nuoi import vi_pham_nuoi_con_nuoi
from adapter.cypher_templates.xu_phat_vi_pham.vi_pham_van_phong_con_nuoi_nuoc_ngoai import vi_pham_van_phong_con_nuoi_nuoc_ngoai
from adapter.cypher_templates.xu_phat_vi_pham.bao_luc_the_chat_nguoc_dai import bao_luc_the_chat_nguoc_dai
from adapter.cypher_templates.xu_phat_vi_pham.bo_mac_khong_cham_soc_giao_duc import bo_mac_khong_cham_soc_giao_duc
from adapter.cypher_templates.xu_phat_vi_pham.xuc_pham_danh_du_bi_mat import xuc_pham_danh_du_bi_mat
from adapter.cypher_templates.xu_phat_vi_pham.co_lap_ap_luc_tam_ly import co_lap_ap_luc_tam_ly
from adapter.cypher_templates.xu_phat_vi_pham.bao_luc_tinh_duc import bao_luc_tinh_duc
from adapter.cypher_templates.xu_phat_vi_pham.ngan_can_tham_nom_cham_soc import ngan_can_tham_nom_cham_soc
from adapter.cypher_templates.xu_phat_vi_pham.vi_pham_cap_duong_nuoi_duong import vi_pham_cap_duong_nuoi_duong
from adapter.cypher_templates.xu_phat_vi_pham.bao_luc_kinh_te import bao_luc_kinh_te
from adapter.cypher_templates.xu_phat_vi_pham.cuong_ep_ra_khoi_cho_o import cuong_ep_ra_khoi_cho_o
from adapter.cypher_templates.xu_phat_vi_pham.bao_luc_nguoi_bao_tin_giup_do import bao_luc_nguoi_bao_tin_giup_do
from adapter.cypher_templates.xu_phat_vi_pham.xui_giuc_cuong_ep_bao_luc import xui_giuc_cuong_ep_bao_luc
from adapter.cypher_templates.xu_phat_vi_pham.vi_pham_ngan_chan_bao_tin_xu_ly import vi_pham_ngan_chan_bao_tin_xu_ly
from adapter.cypher_templates.xu_phat_vi_pham.truyen_ba_kich_dong_bao_luc import truyen_ba_kich_dong_bao_luc
from adapter.cypher_templates.xu_phat_vi_pham.tiet_lo_thong_tin_va_bang_gia import tiet_lo_thong_tin_va_bang_gia
from adapter.cypher_templates.xu_phat_vi_pham.loi_dung_hoat_dong_phong_chong_bao_luc import loi_dung_hoat_dong_phong_chong_bao_luc
from adapter.cypher_templates.xu_phat_vi_pham.vi_pham_dang_ky_co_so_tro_giup import vi_pham_dang_ky_co_so_tro_giup
from adapter.cypher_templates.xu_phat_vi_pham.vi_pham_cam_tiep_xuc import vi_pham_cam_tiep_xuc
from adapter.cypher_templates.xu_phat_vi_pham.hanh_vi_bi_cam_hngd_tong_quat import hanh_vi_bi_cam_hngd_tong_quat

XU_PHAT_VI_PHAM_REGISTRY = TemplateRegistry(topic="xu_phat_vi_pham")
XU_PHAT_VI_PHAM_REGISTRY.register(xu_phat_ket_hon_ly_hon_tong_quat)
XU_PHAT_VI_PHAM_REGISTRY.register(tao_hon_va_to_chuc_tao_hon)
XU_PHAT_VI_PHAM_REGISTRY.register(vi_pham_mot_vo_mot_chong)
XU_PHAT_VI_PHAM_REGISTRY.register(can_tro_cuong_ep_ket_hon_ly_hon)
XU_PHAT_VI_PHAM_REGISTRY.register(quan_he_hon_nhan_bi_cam_vphc)
XU_PHAT_VI_PHAM_REGISTRY.register(toi_loan_luan_hinh_su)
XU_PHAT_VI_PHAM_REGISTRY.register(ket_hon_ly_hon_gia_tao)
XU_PHAT_VI_PHAM_REGISTRY.register(sinh_con_mang_thai_ho_thuong_mai)
XU_PHAT_VI_PHAM_REGISTRY.register(vi_pham_giam_ho)
XU_PHAT_VI_PHAM_REGISTRY.register(vi_pham_nuoi_con_nuoi)
XU_PHAT_VI_PHAM_REGISTRY.register(vi_pham_van_phong_con_nuoi_nuoc_ngoai)
XU_PHAT_VI_PHAM_REGISTRY.register(bao_luc_the_chat_nguoc_dai)
XU_PHAT_VI_PHAM_REGISTRY.register(bo_mac_khong_cham_soc_giao_duc)
XU_PHAT_VI_PHAM_REGISTRY.register(xuc_pham_danh_du_bi_mat)
XU_PHAT_VI_PHAM_REGISTRY.register(co_lap_ap_luc_tam_ly)
XU_PHAT_VI_PHAM_REGISTRY.register(bao_luc_tinh_duc)
XU_PHAT_VI_PHAM_REGISTRY.register(ngan_can_tham_nom_cham_soc)
XU_PHAT_VI_PHAM_REGISTRY.register(vi_pham_cap_duong_nuoi_duong)
XU_PHAT_VI_PHAM_REGISTRY.register(bao_luc_kinh_te)
XU_PHAT_VI_PHAM_REGISTRY.register(cuong_ep_ra_khoi_cho_o)
XU_PHAT_VI_PHAM_REGISTRY.register(bao_luc_nguoi_bao_tin_giup_do)
XU_PHAT_VI_PHAM_REGISTRY.register(xui_giuc_cuong_ep_bao_luc)
XU_PHAT_VI_PHAM_REGISTRY.register(vi_pham_ngan_chan_bao_tin_xu_ly)
XU_PHAT_VI_PHAM_REGISTRY.register(truyen_ba_kich_dong_bao_luc)
XU_PHAT_VI_PHAM_REGISTRY.register(tiet_lo_thong_tin_va_bang_gia)
XU_PHAT_VI_PHAM_REGISTRY.register(loi_dung_hoat_dong_phong_chong_bao_luc)
XU_PHAT_VI_PHAM_REGISTRY.register(vi_pham_dang_ky_co_so_tro_giup)
XU_PHAT_VI_PHAM_REGISTRY.register(vi_pham_cam_tiep_xuc)
XU_PHAT_VI_PHAM_REGISTRY.register(hanh_vi_bi_cam_hngd_tong_quat)

__all__ = [
    "XU_PHAT_VI_PHAM_REGISTRY",
    "xu_phat_ket_hon_ly_hon_tong_quat",
    "tao_hon_va_to_chuc_tao_hon",
    "vi_pham_mot_vo_mot_chong",
    "can_tro_cuong_ep_ket_hon_ly_hon",
    "quan_he_hon_nhan_bi_cam_vphc",
    "toi_loan_luan_hinh_su",
    "ket_hon_ly_hon_gia_tao",
    "sinh_con_mang_thai_ho_thuong_mai",
    "vi_pham_giam_ho",
    "vi_pham_nuoi_con_nuoi",
    "vi_pham_van_phong_con_nuoi_nuoc_ngoai",
    "bao_luc_the_chat_nguoc_dai",
    "bo_mac_khong_cham_soc_giao_duc",
    "xuc_pham_danh_du_bi_mat",
    "co_lap_ap_luc_tam_ly",
    "bao_luc_tinh_duc",
    "ngan_can_tham_nom_cham_soc",
    "vi_pham_cap_duong_nuoi_duong",
    "bao_luc_kinh_te",
    "cuong_ep_ra_khoi_cho_o",
    "bao_luc_nguoi_bao_tin_giup_do",
    "xui_giuc_cuong_ep_bao_luc",
    "vi_pham_ngan_chan_bao_tin_xu_ly",
    "truyen_ba_kich_dong_bao_luc",
    "tiet_lo_thong_tin_va_bang_gia",
    "loi_dung_hoat_dong_phong_chong_bao_luc",
    "vi_pham_dang_ky_co_so_tro_giup",
    "vi_pham_cam_tiep_xuc",
    "hanh_vi_bi_cam_hngd_tong_quat",
]
